apiVersion: depnoyed/v1
name: nginx-proxy
display:
  name: "NGINX Proxy"
  category: "Web"
  description: "High-performance HTTP server and reverse proxy."
runtime:
  type: "container"
  image: "nginx:alpine"
  port: 80
resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"
storage:
  - name: "data"
    mountPath: "/etc/nginx"
    size: "1Gi"
health:
  http:
    path: "/"
    port: 80