apiVersion: depnoyed/v1
name: n8n
display:
  name: "n8n"
  category: "Productivity"
  description: "Free and open node based Workflow Automation Tool. Easily automate tasks across different services."
runtime:
  type: "container"
  image: "n8nio/n8n:latest"
  port: 5678
resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "2Gi"
storage:
  - name: "data"
    mountPath: "/home/node/.n8n"
    size: "5Gi"
health:
  http:
    path: "/healthz"
    port: 5678