apiVersion: depnoyed/v1
name: prometheus
display:
  name: "Prometheus"
  category: "Monitoring"
  description: "Monitoring system and time series database."
runtime:
  type: "container"
  image: "prom/prometheus:latest"
  port: 9090
resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "2Gi"
storage:
  - name: "data"
    mountPath: "/prometheus"
    size: "20Gi"
health:
  http:
    path: "/-/healthy"
    port: 9090